name: Train and Upload Models to S3

on:
  push:
    branches: [ main ]

jobs:
  train-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training script
      run: python train.py

    - name: Upload models to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: |
        python3 -c "
import boto3, os
s3 = boto3.client('s3', region_name='${{ secrets.AWS_REGION }}')
for file in os.listdir('models'):
    s3.upload_file(f'models/{file}', '${{ secrets.S3_BUCKET_NAME }}', f'models/{file}')
print('Models uploaded to S3.')
        "
